Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,8 +7,8 @@ on:
 env:
   AWS_REGION: us-east-2                     # Set this to your AWS region, e.g., us-west-1
   EB_APPLICATION_NAME: VinylRecordsApp      # Set this to your Elastic Beanstalk application name
-  EB_ENVIRONMENT_NAME: VinylRecordsApp-env      # Set this to your Elastic Beanstalk environment name
-  EB_BUCKET_NAME: vly2121            # Set this to your S3 bucket for storing application versions
+  EB_ENVIRONMENT_NAME: VinylRecordsApp-env  # Set this to your Elastic Beanstalk environment name
+  EB_BUCKET_NAME: vly2121                  # Set this to your S3 bucket for storing application versions
   IMAGE_TAG: ${{ github.sha }}             # Image tag based on Git commit SHA
 
 permissions:
@@ -24,10 +24,10 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v4
 
-    - name: Set up Python
+    - name: Set up Python 3.12
       uses: actions/setup-python@v4
       with:
-        python-version: '3.12'  # Set to the Python version you are using
+        python-version: '3.12'
 
     - name: Install dependencies
       run: |
@@ -56,8 +56,18 @@ jobs:
       run: |
         aws s3 cp application.zip s3://${{ env.EB_BUCKET_NAME }}/application.zip
 
+    - name: Create Elastic Beanstalk Environment if it doesn't exist
+      run: |
+        # Check if the environment exists, and create it if not
+        if ! eb describe environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }}; then
+          echo "Environment not found, creating..."
+          eb create ${{ env.EB_ENVIRONMENT_NAME }} --region ${{ env.AWS_REGION }} --single
+        else
+          echo "Environment exists."
+        fi
+
     - name: Deploy to Elastic Beanstalk
       run: |
-        eb init -p python-3.8 ${{ env.EB_APPLICATION_NAME }} --region ${{ env.AWS_REGION }} --no-verify-ssl
+        eb init -p python-3.12 ${{ env.EB_APPLICATION_NAME }} --region ${{ env.AWS_REGION }} --no-verify-ssl
         eb use ${{ env.EB_ENVIRONMENT_NAME }}
         eb deploy --no-verify-ssl
